# Generated by Django 4.1 on 2022-08-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='losses',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.SmallIntegerField(),
        ),
    ]
