# Generated by Django 4.1 on 2022-08-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0003_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='rebounds',
            field=models.FloatField(),
        ),
    ]
