# Generated by Django 4.1 on 2022-08-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0004_alter_player_assists_alter_player_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='injured',
            field=models.CharField(default='Enter or Yes/No', max_length=3),
        ),
    ]
